version: '3'

services:
  traefik:
    image: traefik:v2.6
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.http.routers.dash.rule: Host(`dash.localhost`)
      traefik.http.routers.dash.service: api@internal
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    command: node server/dist/index.js
    labels:
      traefik.http.routers.server.rule: Host(`teledrive.localhost`)
      traefik.port: 4000
    ports:
      - "4000:4000"
    expose:
      - 4000
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        REACT_APP_TG_API_ID: ${TG_API_ID}
        REACT_APP_TG_API_HASH: ${TG_API_HASH}
    environment:
      DB_NAME: teledrive
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: teledrive
    volumes:
      - ../server/src/model/migrations/dump.sql:/docker-entrypoint-initdb.d/dump.sql