on:
  push:
    branches:
      - staging

name: Build Staging

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn install
    - run: REACT_APP_API_URL=https://teledrive.vercel.app yarn workspaces run build
    - run: npm i vercel -g
    - name: "Deploy to Vercel"
      run: npx vercel --token ${VERCEL_TOKEN} --prod
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    - run: curl https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TG_BOT_OWNER_ID }}&text=%F0%9F%8E%89%20*Deployed%20to%20staging*%0A%0APlease%20take%20a%20look%3A%20https%3A%2F%2Fteledrive.vercel.app&parse_mode=markdown